# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/djmall_zw?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false

  mail:
    host: smtp.qq.com #SMTP服务器地址
    port: 25
    username: 1392495684@qq.com #登陆账号
    password: rcfwuyxfwulkgiad #登陆密码（或授权码）

# Mybatis-plus
mybatis-plus:
  type-aliases-package: com.dj.mall.auth.entity # 类别名
  mapper-locations: classpath:/mapper/**/*.xml # mapper文件
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射

# Dubbo
dubbo:
  application:
    name: service # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  protocol:
    name: dubbo # 协议名
    port: 20880 # 服务端口
  consumer:
    timeout: 60000
    check: false

# 日志
logging:
  level:
    com.dj.mall.auth.mapper:
      debug