spring:
  rabbitmq:
    host: 192.168.85.131
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    connection-timeout: 60000

# Dubbo
dubbo:
  application:
    name: task # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  consumer:
    check: false
    timeout: 60000
