# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/djmall_zw?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
  rabbitmq:
    host: 192.168.85.131
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    connection-timeout: 60000

# Mybatis-plus
mybatis-plus:
  type-aliases-package: com.dj.mall.order.entity # 类别名
  mapper-locations: classpath:/mapper/**/*.xml # mapper文件
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射

# Dubbo
dubbo:
  application:
    name: order-service # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  protocol:
    name: dubbo # 协议名
    port: 20885 # 服务端口
  consumer:
    timeout: 60000
    check: false

# 日志
logging:
  level:
    com.dj.mall.order.mapper:
      debug
server:
  port: 8086
