server:
  port: 8085
  servlet:
    context-path: /platform
    jsp:
      init-parameters:
        development: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true # Rest 隐藏表单过滤
# Dubbo
dubbo:
  application:
    name: platform # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  protocol:
    name: dubbo
    port: 20881
  consumer:
    check: false
    timeout: 60000
